### ISSUE TITLE
ЛР 3

### ISSUE THREAD

**Issue by alexandr-kaa** [Fllaksi/OSRV_Kalmykov#1]
Переотправкой ответа поместите проверку принятого сообщения на свое ФИО. Если совпало то д.б. один ответ, иначе другой.
https://github.com/Fllaksi/OSRV_Kalmykov/blob/124e6c198b19b5a75f19027a76b3eb113930c05d/Laba3/server.c#L26

**Comment by Fllaksi** [comment]
Сделал. Результат приведен на картинке. Если серверу приходит не то сообщение то пишет о том что оно не то что нужно.
